# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets, uic
from desings.menu_window import Ui_MainWindow
import sys
import os
from os.path import expanduser

class FilesData(object):
    def __init__(self):
        self.files_names = []
        self.template_name = ""

    def set_files_names(self, list_of_names):
        self.files_names = list_of_names

    def set_template_name(self, template_name):
        self.template_name = template_name

    def print_files_data(self):
        print(self.files_names , "\n-----------\n", self.template_name)


class mywindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(mywindow, self).__init__()
        self.setWindowTitle("ConstructorMainMenu")
        self.setMinimumSize(1500, 800)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.DataDirectories = FilesData()

        self.ui.pushButton.clicked.connect(self.ObjectToArray)
        self.ui.pushButton_2.clicked.connect(self.DownloadTemplateName)
        self.ui.pushButton_3.clicked.connect(self.NextWindow)

    def ObjectToArray(self):
        directory = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Directory")
        files_names = os.listdir(directory)
        self.DataDirectories.set_files_names(files_names)

    def DownloadTemplateName(self):
        filename = QtWidgets.QFileDialog.getOpenFileName(self, "Select file")
        self.DataDirectories.set_template_name(filename[0])
        print(self.DataDirectories.print_files_data())

    def GetListOfFiles(self):
        return files_names

    def NextWindow(self):
        a = 1

app = QtWidgets.QApplication([])
application = mywindow()
application.show()

sys.exit(app.exec())